### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by Sergey2311** [Sergey2311/frontend7-8#1]
Работает удаление и дизлайки. 
Добавление и лайки не получается сделать. Вроде все делал по аналогии. 

![71120296-2af6bb00-21ed-11ea-80f7-8978109faa38 1](https://user-images.githubusercontent.com/55457504/71120365-4cf03d80-21ed-11ea-91d0-ff595e5c0342.png)
)

**Comment by Sergey2311** [comment]
https://sergey2311.github.io/frontend7-8/

**Comment by coursar** [comment]
Запустите локально и смотрите на логи сервера, в чём ошибка.
